/**
 * `aws:kms:Key` handler (@aws-sdk/client-kms) — customer-managed CMK for the
 * encryption posture (M22.2).
 *
 * IDENTITY: KMS keys have no caller-chosen name — the key id is generated by
 * AWS. The handler therefore OWNS AN ALIAS as the stable identity:
 * `alias/<resourceIdOf(resource)>`. Every read resolves through the alias;
 * create points the alias at the fresh key; delete removes the alias before
 * scheduling the key itself.
 *
 * read   → DescribeKey with KeyId='alias/<name>' (NotFoundException → absent)
 *          + ListResourceTags with the resolved key id. A key whose KeyState
 *          is PendingDeletion or PendingReplicaDeletion reads as ABSENT (the
 *          secrets-manager "scheduled for deletion" idiom).
 * create → CreateKey (description/keySpec/keyUsage, tags at creation) then
 *          CreateAlias. NEVER CancelKeyDeletion: a pending-deletion key is
 *          never resurrected — but its alias may still exist, and KMS forbids
 *          re-creating an alias that is still pointed at the dying key, so
 *          create first drops a stale alias that targets a pending-deletion
 *          key, then mints a fresh key and repoints the identity.
 * update → UpdateKeyDescription (description drift), EnableKey/DisableKey
 *          (enabled drift), TagResource (tag reconciliation).
 * delete → DeleteAlias then ScheduleKeyDeletion with PendingWindowInDays=7 —
 *          the AWS MINIMUM; KMS forbids immediate deletion. PendingDeletion is
 *          the AWS-mandated terminal state: the post-run sweep must treat
 *          KeyState=PendingDeletion as deleted (the alias, our identity, IS
 *          gone immediately).
 */

import {
  CreateAliasCommand,
  CreateKeyCommand,
  DeleteAliasCommand,
  DescribeKeyCommand,
  DisableKeyCommand,
  EnableKeyCommand,
  ListResourceTagsCommand,
  ScheduleKeyDeletionCommand,
  TagResourceCommand,
  UpdateKeyDescriptionCommand,
} from '@aws-sdk/client-kms';
import type { KMSClient, KeySpec, KeyUsageType, Tag } from '@aws-sdk/client-kms';
import type { PlanResource } from '@iap/provider-sdk';
import type { ResourceState, TargetHandler } from './types.js';
import { isManaged } from './tags.js';
import { nameMatches, resourceIdOf, scalarStr } from './util.js';

const NOT_FOUND = ['NotFoundException'] as const;

/** KeyStates that mean "on its way out" — read as absent, never resurrect. */
const PENDING_DELETION_STATES = ['PendingDeletion', 'PendingReplicaDeletion'] as const;

function isPendingDeletion(keyState: string | undefined): boolean {
  return PENDING_DELETION_STATES.some((state) => state === keyState);
}

/** The handler-owned stable identity: `alias/<resourceId>`. */
function aliasNameOf(resource: PlanResource): string {
  return `alias/${resourceIdOf(resource)}`;
}

/** KMS tags use `{ TagKey, TagValue }`, not the `{ Key, Value }` of tags.ts. */
function toKmsTagList(tags: Record<string, string>): Tag[] {
  return Object.keys(tags)
    .sort()
    .map((key) => ({ TagKey: key, TagValue: tags[key] ?? '' }));
}

function fromKmsTagList(
  list: ReadonlyArray<{ TagKey?: string | undefined; TagValue?: string | undefined }>,
): Record<string, string> {
  const tags: Record<string, string> = {};
  for (const entry of list) {
    if (entry.TagKey !== undefined) tags[entry.TagKey] = entry.TagValue ?? '';
  }
  return tags;
}

export class KmsKeyHandler implements TargetHandler {
  static readonly targetType = 'aws:kms:Key' as const;
  readonly targetType = KmsKeyHandler.targetType;
  /** Cryptographic shape is fixed at creation (ADR-0006) — drift replaces. */
  readonly immutableProjectionKeys = ['keySpec', 'keyUsage'] as const;

  constructor(private readonly client: KMSClient) {}

  desiredProjection(resource: PlanResource): Record<string, string> {
    const a = resource.desiredAttributes;
    return {
      keySpec: scalarStr(a['keySpec']) || 'SYMMETRIC_DEFAULT',
      keyUsage: scalarStr(a['keyUsage']) || 'ENCRYPT_DECRYPT',
      description: scalarStr(a['description']),
      enabled: scalarStr(a['enabled']) || 'true',
    };
  }

  async read(resource: PlanResource): Promise<ResourceState> {
    let metadata;
    try {
      const found = await this.client.send(
        new DescribeKeyCommand({ KeyId: aliasNameOf(resource) }),
      );
      metadata = found.KeyMetadata;
    } catch (err) {
      if (nameMatches(err, NOT_FOUND)) {
        return { exists: false, managed: false, tags: {}, projection: {} };
      }
      throw err;
    }
    if (metadata === undefined || isPendingDeletion(metadata.KeyState)) {
      // Scheduled for deletion — treat as absent; create never resurrects it.
      return { exists: false, managed: false, tags: {}, projection: {} };
    }

    // Tag operations take the key id/ARN, never the alias.
    const tagResult = await this.client.send(
      new ListResourceTagsCommand({ KeyId: metadata.KeyId ?? metadata.Arn }),
    );
    const tags = fromKmsTagList(tagResult.Tags ?? []);

    const state: ResourceState = {
      exists: true,
      managed: isManaged(tags),
      tags,
      projection: {
        keySpec: metadata.KeySpec ?? '',
        keyUsage: metadata.KeyUsage ?? '',
        description: metadata.Description ?? '',
        enabled: String(metadata.Enabled ?? false),
      },
    };
    if (metadata.Arn !== undefined) state.identifier = metadata.Arn;
    return state;
  }

  async create(resource: PlanResource, tags: Record<string, string>): Promise<string> {
    const AliasName = aliasNameOf(resource);

    // A pending-deletion key reads as absent, but its alias may still exist —
    // and KMS refuses CreateAlias while the old alias points at the dying key.
    // Drop the stale alias (alias only!) and mint a fresh key. NEVER
    // CancelKeyDeletion — a scheduled deletion is never reversed by create.
    try {
      const stale = await this.client.send(new DescribeKeyCommand({ KeyId: AliasName }));
      if (isPendingDeletion(stale.KeyMetadata?.KeyState)) {
        await this.client.send(new DeleteAliasCommand({ AliasName }));
      }
    } catch (err) {
      if (!nameMatches(err, NOT_FOUND)) throw err;
    }

    const d = this.desiredProjection(resource);
    const description = d['description'] ?? '';
    const created = await this.client.send(
      new CreateKeyCommand({
        ...(description ? { Description: description } : {}),
        KeySpec: d['keySpec'] as KeySpec,
        KeyUsage: d['keyUsage'] as KeyUsageType,
        Tags: toKmsTagList(tags),
      }),
    );
    const keyId = created.KeyMetadata?.KeyId;
    await this.client.send(new CreateAliasCommand({ AliasName, TargetKeyId: keyId }));
    if (d['enabled'] === 'false') {
      // Keys are born enabled; converge a disabled-by-design key immediately.
      await this.client.send(new DisableKeyCommand({ KeyId: keyId }));
    }
    return created.KeyMetadata?.Arn ?? `kms:${AliasName}`;
  }

  async update(resource: PlanResource, current: ResourceState): Promise<void> {
    const KeyId = await this.resolveKeyId(resource, current);
    const d = this.desiredProjection(resource);
    if ((d['description'] ?? '') !== (current.projection['description'] ?? '')) {
      await this.client.send(
        new UpdateKeyDescriptionCommand({ KeyId, Description: d['description'] ?? '' }),
      );
    }
    if ((d['enabled'] ?? 'true') !== (current.projection['enabled'] ?? '')) {
      await this.client.send(
        d['enabled'] === 'false'
          ? new DisableKeyCommand({ KeyId })
          : new EnableKeyCommand({ KeyId }),
      );
    }
    await this.client.send(new TagResourceCommand({ KeyId, Tags: toKmsTagList(current.tags) }));
  }

  async delete(resource: PlanResource, current: ResourceState): Promise<void> {
    // Resolve the key id BEFORE dropping the alias — the alias is the only
    // stable handle we own.
    const KeyId = await this.resolveKeyId(resource, current);
    await this.client.send(new DeleteAliasCommand({ AliasName: aliasNameOf(resource) }));
    // KMS forbids immediate key deletion; 7 days is the AWS minimum window.
    // The key parks in PendingDeletion (terminal, fail-closed teardown) — the
    // post-run sweep must accept KeyState=PendingDeletion as deleted.
    await this.client.send(new ScheduleKeyDeletionCommand({ KeyId, PendingWindowInDays: 7 }));
  }

  /** Key id/ARN for the alias-averse operations (tag/enable/disable/delete). */
  private async resolveKeyId(resource: PlanResource, current: ResourceState): Promise<string> {
    if (current.identifier !== undefined) return current.identifier;
    const found = await this.client.send(
      new DescribeKeyCommand({ KeyId: aliasNameOf(resource) }),
    );
    return found.KeyMetadata?.Arn ?? found.KeyMetadata?.KeyId ?? '';
  }
}
