/**
 * M23.4 — network routing/egress (Network kind) handlers, @aws-sdk/client-ec2.
 * Three tag-identity handlers for the VPC egress graph:
 *
 *   InternetGatewayHandler ('aws:ec2:InternetGateway')
 *   RouteTableHandler      ('aws:ec2:RouteTable')
 *   NatGatewayHandler      ('aws:ec2:NatGateway')
 *
 * IDENTITY (shared idiom with ec2-volume / ec2-instance): IGW / route-table /
 * NAT ids are generated by AWS, so each handler OWNS the `iap:resourceId` tag
 * (value = the plan logicalId, exactly what buildTags stamps) as the stable
 * identity. read filters DescribeXxx on that tag; a `Name` tag (= resourceId)
 * rides along for console humans; ALL tags are set at create via
 * TagSpecifications (these resources cannot be tagged-into-identity later —
 * tags at create or never). MORE THAN ONE live match is an ambiguous identity
 * and fails closed with a loud error — the handler never guesses which it owns.
 *
 * CROSS-RESOURCE REFERENCES: the VPC graph is stitched by id attributes that
 * the engine has already resolved to concrete AWS ids before execution reaches
 * a handler:
 *   - IGW / RouteTable  ← `vpcId`     (the VPC to attach / own the table)
 *   - RouteTable        ← `subnetId`  (optional public-subnet association)
 *   - RouteTable routes ← `routes`    (see serialization below)
 *   - NAT               ← `subnetId`  (the public subnet the NAT lives in)
 * A required reference that is absent fails closed — the handler never invents
 * a VPC / subnet / gateway id.
 *
 * ROUTE SERIALIZATION (`routes` attr): a compact, comma-separated string of
 * `<destinationCidr>:<targetKind>:<targetId>` entries, targetKind ∈ {igw,nat},
 * targetId the resolved IGW / NAT id (a cross-resource ref). IPv4 only for v1
 * (the ':' split is unambiguous because IPv4 CIDRs carry none). Example:
 *   `0.0.0.0/0:igw:igw-abc123,10.1.0.0/16:nat:nat-xyz789`
 * The VPC-local route (GatewayId 'local') is AWS-managed and never modelled.
 *
 * IMMUTABILITY (ADR-0006 → gated replace, never in-place update):
 *   - IGW  `vpcId`: re-attaching to a different VPC is a detach+attach; v1
 *     models it as replace (delete+create) rather than orchestrate the reattach.
 *   - RouteTable `vpcId`: a route table belongs to one VPC for life.
 *     `routes` and `subnetAssociation` ARE mutable (diffed in update()).
 *   - NAT `subnetId` and `connectivityType`: fixed at creation. NAT gateways
 *     have NO mutable attributes in scope, so any non-identity change replaces.
 */

import {
  AllocateAddressCommand,
  AssociateRouteTableCommand,
  AttachInternetGatewayCommand,
  CreateInternetGatewayCommand,
  CreateNatGatewayCommand,
  CreateRouteCommand,
  CreateRouteTableCommand,
  DeleteInternetGatewayCommand,
  DeleteNatGatewayCommand,
  DeleteRouteCommand,
  DeleteRouteTableCommand,
  DescribeAddressesCommand,
  DescribeInternetGatewaysCommand,
  DescribeNatGatewaysCommand,
  DescribeRouteTablesCommand,
  DetachInternetGatewayCommand,
  DisassociateRouteTableCommand,
  ReleaseAddressCommand,
  ReplaceRouteCommand,
} from '@aws-sdk/client-ec2';
import type { EC2Client, RouteTable } from '@aws-sdk/client-ec2';
import type { PlanResource } from '@iap/provider-sdk';
import type { ResourceState, TargetHandler } from './types.js';
import { RESOURCE_TAG_KEY, fromTagList, isManaged, toTagList } from './tags.js';
import { resourceIdOf, scalarStr } from './util.js';

/** NAT states that count as "live" for identity resolution (else absent). */
const LIVE_NAT_STATES = ['pending', 'available'] as const;

/**
 * NAT states in which the Elastic IP is STILL BOUND to the gateway — the delete
 * waiter must poll these out (not merely `pending`/`available`) before releasing
 * the EIP. A NAT in `deleting` has not yet freed its EIP, so releasing it there
 * races AWS and fails ("You do not have permission to access the specified
 * resource" — an M23.4 live-run finding); only `deleted`/`failed`/absent is safe.
 */
const NAT_EIP_BOUND_STATES = ['pending', 'available', 'deleting'] as const;

/** A parsed route: destination CIDR → its egress target. */
interface RouteTarget {
  kind: 'igw' | 'nat';
  target: string;
}

/**
 * Parse the compact `routes` attribute into a CIDR→target map. Malformed or
 * empty entries are skipped (the empty attr → an empty map, i.e. no managed
 * routes beyond the AWS-managed local route).
 */
function parseRoutes(serialized: string): Map<string, RouteTarget> {
  const map = new Map<string, RouteTarget>();
  for (const entry of serialized.split(',')) {
    const trimmed = entry.trim();
    if (trimmed === '') continue;
    const parts = trimmed.split(':');
    const cidr = parts[0] ?? '';
    const kind = parts[1] ?? '';
    const target = parts.slice(2).join(':');
    if (cidr === '' || target === '' || (kind !== 'igw' && kind !== 'nat')) continue;
    map.set(cidr, { kind, target });
  }
  return map;
}

/** Deterministic serialization of a route map (sorted by CIDR) for drift. */
function serializeRoutes(map: Map<string, RouteTarget>): string {
  return [...map.keys()]
    .sort()
    .map((cidr) => {
      const t = map.get(cidr) as RouteTarget;
      return `${cidr}:${t.kind}:${t.target}`;
    })
    .join(',');
}

export class InternetGatewayHandler implements TargetHandler {
  static readonly targetType = 'aws:ec2:InternetGateway' as const;
  readonly targetType = InternetGatewayHandler.targetType;
  /** The attachment (vpcId) is fixed for v1 — a re-attach is a gated replace. */
  readonly immutableProjectionKeys = ['vpcId'] as const;

  constructor(private readonly ec2: EC2Client) {}

  desiredProjection(resource: PlanResource): Record<string, string> {
    return { vpcId: scalarStr(resource.desiredAttributes['vpcId']) };
  }

  async read(resource: PlanResource): Promise<ResourceState> {
    const found = await this.ec2.send(
      new DescribeInternetGatewaysCommand({
        Filters: [{ Name: `tag:${RESOURCE_TAG_KEY}`, Values: [resource.logicalId] }],
      }),
    );
    const gateways = found.InternetGateways ?? [];
    if (gateways.length > 1) {
      throw new Error(
        `ambiguous internet-gateway identity: ${gateways.length} gateways carry ` +
          `${RESOURCE_TAG_KEY}=${resource.logicalId} (${gateways
            .map((g) => g.InternetGatewayId ?? '?')
            .join(', ')}) — refusing to guess (fail closed)`,
      );
    }
    const igw = gateways[0];
    if (igw === undefined) {
      return { exists: false, managed: false, tags: {}, projection: {} };
    }
    const tags = fromTagList(igw.Tags ?? []);
    // The attachment (if any) is the vpcId projection — an attached VPC other
    // than the desired one is immutable drift → replace.
    const attachedVpc =
      (igw.Attachments ?? []).map((a) => a.VpcId).find((v) => v !== undefined) ?? '';
    const state: ResourceState = {
      exists: true,
      managed: isManaged(tags),
      tags,
      projection: { vpcId: attachedVpc },
    };
    if (igw.InternetGatewayId !== undefined) state.identifier = igw.InternetGatewayId;
    return state;
  }

  async create(resource: PlanResource, tags: Record<string, string>): Promise<string> {
    const vpcId = scalarStr(resource.desiredAttributes['vpcId']);
    if (vpcId === '') {
      throw new Error(
        `aws:ec2:InternetGateway '${resourceIdOf(resource)}' requires attribute 'vpcId' ` +
          '(the VPC to attach to) — refusing to create a detached gateway (fail closed)',
      );
    }
    const created = await this.ec2.send(
      new CreateInternetGatewayCommand({
        TagSpecifications: [
          {
            ResourceType: 'internet-gateway',
            Tags: toTagList({ Name: resourceIdOf(resource), ...tags }),
          },
        ],
      }),
    );
    const igwId = created.InternetGateway?.InternetGatewayId;
    if (igwId === undefined) {
      throw new Error(
        `CreateInternetGateway returned no id for ${resource.logicalId} (fail closed)`,
      );
    }
    try {
      // Attach as a second step — an IGW is created detached (order matters).
      await this.ec2.send(
        new AttachInternetGatewayCommand({ InternetGatewayId: igwId, VpcId: vpcId }),
      );
    } catch (err) {
      // A created-but-unattached IGW is dangling: tear it back down so the next
      // apply retries cleanly rather than tripping ambiguous identity.
      try {
        await this.ec2.send(new DeleteInternetGatewayCommand({ InternetGatewayId: igwId }));
      } catch {
        /* best effort — surface the ORIGINAL attach failure */
      }
      throw err;
    }
    return igwId;
  }

  async update(_resource: PlanResource, _current: ResourceState): Promise<void> {
    // The only projection key (vpcId) is immutable, so the classifier never
    // routes drift here — there is no in-place reconcile for an IGW in v1.
  }

  async delete(resource: PlanResource, current: ResourceState): Promise<void> {
    if (current.identifier === undefined) {
      throw new Error(
        `aws:ec2:InternetGateway '${resourceIdOf(resource)}': no live gateway id to delete (fail closed)`,
      );
    }
    const igwId = current.identifier;
    // ORDER MATTERS: detach from the attached VPC (read from live state) before
    // delete. A detach failure fails closed — deleting an attached IGW is
    // rejected by AWS and would leave the graph half-torn.
    const attachedVpc = current.projection['vpcId'] ?? '';
    if (attachedVpc !== '') {
      await this.ec2.send(
        new DetachInternetGatewayCommand({ InternetGatewayId: igwId, VpcId: attachedVpc }),
      );
    }
    await this.ec2.send(new DeleteInternetGatewayCommand({ InternetGatewayId: igwId }));
  }
}

export class RouteTableHandler implements TargetHandler {
  static readonly targetType = 'aws:ec2:RouteTable' as const;
  readonly targetType = RouteTableHandler.targetType;
  /** A route table belongs to one VPC for life; routes/association are mutable. */
  readonly immutableProjectionKeys = ['vpcId'] as const;

  constructor(private readonly ec2: EC2Client) {}

  desiredProjection(resource: PlanResource): Record<string, string> {
    const a = resource.desiredAttributes;
    return {
      vpcId: scalarStr(a['vpcId']),
      routes: serializeRoutes(parseRoutes(scalarStr(a['routes']))),
      subnetAssociation: scalarStr(a['subnetId']),
    };
  }

  /** Resolve the live route table by identity tag; >1 fails closed. */
  private async findRouteTable(resource: PlanResource): Promise<RouteTable | undefined> {
    const found = await this.ec2.send(
      new DescribeRouteTablesCommand({
        Filters: [{ Name: `tag:${RESOURCE_TAG_KEY}`, Values: [resource.logicalId] }],
      }),
    );
    const tables = found.RouteTables ?? [];
    if (tables.length > 1) {
      throw new Error(
        `ambiguous route-table identity: ${tables.length} tables carry ` +
          `${RESOURCE_TAG_KEY}=${resource.logicalId} (${tables
            .map((t) => t.RouteTableId ?? '?')
            .join(', ')}) — refusing to guess (fail closed)`,
      );
    }
    return tables[0];
  }

  /** The managed routes of a live table (excludes the AWS 'local' route). */
  private liveRouteMap(table: RouteTable): Map<string, RouteTarget> {
    const map = new Map<string, RouteTarget>();
    for (const route of table.Routes ?? []) {
      const cidr = route.DestinationCidrBlock;
      if (cidr === undefined) continue;
      if (route.GatewayId === 'local') continue; // AWS-managed, never modelled
      if (route.GatewayId !== undefined && route.GatewayId.startsWith('igw-')) {
        map.set(cidr, { kind: 'igw', target: route.GatewayId });
      } else if (route.NatGatewayId !== undefined) {
        map.set(cidr, { kind: 'nat', target: route.NatGatewayId });
      }
    }
    return map;
  }

  /** The first non-main subnet association (id + subnet), if any. */
  private liveAssociation(table: RouteTable): { id: string; subnetId: string } | undefined {
    for (const assoc of table.Associations ?? []) {
      if (assoc.Main === true) continue;
      if (assoc.SubnetId !== undefined && assoc.RouteTableAssociationId !== undefined) {
        return { id: assoc.RouteTableAssociationId, subnetId: assoc.SubnetId };
      }
    }
    return undefined;
  }

  async read(resource: PlanResource): Promise<ResourceState> {
    const table = await this.findRouteTable(resource);
    if (table === undefined) {
      return { exists: false, managed: false, tags: {}, projection: {} };
    }
    const tags = fromTagList(table.Tags ?? []);
    const state: ResourceState = {
      exists: true,
      managed: isManaged(tags),
      tags,
      projection: {
        vpcId: table.VpcId ?? '',
        routes: serializeRoutes(this.liveRouteMap(table)),
        subnetAssociation: this.liveAssociation(table)?.subnetId ?? '',
      },
    };
    if (table.RouteTableId !== undefined) state.identifier = table.RouteTableId;
    return state;
  }

  async create(resource: PlanResource, tags: Record<string, string>): Promise<string> {
    const vpcId = scalarStr(resource.desiredAttributes['vpcId']);
    if (vpcId === '') {
      throw new Error(
        `aws:ec2:RouteTable '${resourceIdOf(resource)}' requires attribute 'vpcId' ` +
          '(the owning VPC) — refusing to create (fail closed)',
      );
    }
    const created = await this.ec2.send(
      new CreateRouteTableCommand({
        VpcId: vpcId,
        TagSpecifications: [
          {
            ResourceType: 'route-table',
            Tags: toTagList({ Name: resourceIdOf(resource), ...tags }),
          },
        ],
      }),
    );
    const rtId = created.RouteTable?.RouteTableId;
    if (rtId === undefined) {
      throw new Error(`CreateRouteTable returned no id for ${resource.logicalId} (fail closed)`);
    }
    // Routes are a second step (the table exists empty but the local route).
    const routes = parseRoutes(scalarStr(resource.desiredAttributes['routes']));
    for (const [cidr, t] of routes) {
      await this.ec2.send(new CreateRouteCommand(this.routeInput(rtId, cidr, t)));
    }
    // Optional subnet association (a public/private subnet routes through us).
    const subnetId = scalarStr(resource.desiredAttributes['subnetId']);
    if (subnetId !== '') {
      await this.ec2.send(
        new AssociateRouteTableCommand({ RouteTableId: rtId, SubnetId: subnetId }),
      );
    }
    return rtId;
  }

  async update(resource: PlanResource, current: ResourceState): Promise<void> {
    const table = await this.findRouteTable(resource);
    const rtId = table?.RouteTableId ?? current.identifier;
    if (rtId === undefined || table === undefined) {
      throw new Error(
        `aws:ec2:RouteTable '${resourceIdOf(resource)}': no live route table to reconcile (fail closed)`,
      );
    }
    const desired = parseRoutes(scalarStr(resource.desiredAttributes['routes']));
    const live = this.liveRouteMap(table);

    // Routes removed from desired → DeleteRoute.
    for (const cidr of live.keys()) {
      if (!desired.has(cidr)) {
        await this.ec2.send(
          new DeleteRouteCommand({ RouteTableId: rtId, DestinationCidrBlock: cidr }),
        );
      }
    }
    // Routes added or re-targeted → CreateRoute / ReplaceRoute.
    for (const [cidr, t] of desired) {
      const existing = live.get(cidr);
      if (existing === undefined) {
        await this.ec2.send(new CreateRouteCommand(this.routeInput(rtId, cidr, t)));
      } else if (existing.kind !== t.kind || existing.target !== t.target) {
        await this.ec2.send(new ReplaceRouteCommand(this.routeInput(rtId, cidr, t)));
      }
    }

    // Subnet association drift → Disassociate old, Associate new.
    const desiredSubnet = scalarStr(resource.desiredAttributes['subnetId']);
    const liveAssoc = this.liveAssociation(table);
    if (desiredSubnet !== (liveAssoc?.subnetId ?? '')) {
      if (liveAssoc !== undefined) {
        await this.ec2.send(new DisassociateRouteTableCommand({ AssociationId: liveAssoc.id }));
      }
      if (desiredSubnet !== '') {
        await this.ec2.send(
          new AssociateRouteTableCommand({ RouteTableId: rtId, SubnetId: desiredSubnet }),
        );
      }
    }
  }

  async delete(resource: PlanResource, current: ResourceState): Promise<void> {
    const table = await this.findRouteTable(resource);
    const rtId = table?.RouteTableId ?? current.identifier;
    if (rtId === undefined) {
      throw new Error(
        `aws:ec2:RouteTable '${resourceIdOf(resource)}': no live route table id to delete (fail closed)`,
      );
    }
    // Disassociate any (non-main) subnet associations first — an associated
    // table cannot be deleted (fail closed if any disassociation fails).
    for (const assoc of table?.Associations ?? []) {
      if (assoc.Main === true) continue;
      if (assoc.RouteTableAssociationId !== undefined) {
        await this.ec2.send(
          new DisassociateRouteTableCommand({ AssociationId: assoc.RouteTableAssociationId }),
        );
      }
    }
    await this.ec2.send(new DeleteRouteTableCommand({ RouteTableId: rtId }));
  }

  /** Build the CreateRoute/ReplaceRoute input for a target kind. */
  private routeInput(
    rtId: string,
    cidr: string,
    t: RouteTarget,
  ): {
    RouteTableId: string;
    DestinationCidrBlock: string;
    GatewayId?: string;
    NatGatewayId?: string;
  } {
    return {
      RouteTableId: rtId,
      DestinationCidrBlock: cidr,
      ...(t.kind === 'igw' ? { GatewayId: t.target } : { NatGatewayId: t.target }),
    };
  }
}

export class NatGatewayHandler implements TargetHandler {
  static readonly targetType = 'aws:ec2:NatGateway' as const;
  readonly targetType = NatGatewayHandler.targetType;
  /**
   * subnetId and connectivityType are fixed at creation. NAT gateways have NO
   * mutable attributes in scope, so ANY non-identity change is a gated replace.
   */
  readonly immutableProjectionKeys = ['subnetId', 'connectivityType'] as const;

  constructor(private readonly ec2: EC2Client) {}

  desiredProjection(resource: PlanResource): Record<string, string> {
    const a = resource.desiredAttributes;
    return {
      subnetId: scalarStr(a['subnetId']),
      connectivityType: scalarStr(a['connectivityType']) || 'public',
    };
  }

  async read(resource: PlanResource): Promise<ResourceState> {
    // NAT DescribeNatGateways uses `Filter` (not `Filters`).
    const found = await this.ec2.send(
      new DescribeNatGatewaysCommand({
        Filter: [{ Name: `tag:${RESOURCE_TAG_KEY}`, Values: [resource.logicalId] }],
      }),
    );
    // deleting/deleted/failed states read as absent — a dying NAT is never
    // resurrected and its create mints a fresh one.
    const gateways = (found.NatGateways ?? []).filter((g) =>
      LIVE_NAT_STATES.some((s) => s === g.State),
    );
    if (gateways.length > 1) {
      throw new Error(
        `ambiguous NAT-gateway identity: ${gateways.length} gateways carry ` +
          `${RESOURCE_TAG_KEY}=${resource.logicalId} (${gateways
            .map((g) => g.NatGatewayId ?? '?')
            .join(', ')}) — refusing to guess (fail closed)`,
      );
    }
    const nat = gateways[0];
    if (nat === undefined) {
      return { exists: false, managed: false, tags: {}, projection: {} };
    }
    const tags = fromTagList(nat.Tags ?? []);
    const state: ResourceState = {
      exists: true,
      managed: isManaged(tags),
      tags,
      projection: {
        subnetId: nat.SubnetId ?? '',
        // ConnectivityType defaults to 'public' when the API omits it.
        connectivityType: nat.ConnectivityType ?? 'public',
      },
    };
    if (nat.NatGatewayId !== undefined) state.identifier = nat.NatGatewayId;
    return state;
  }

  async create(resource: PlanResource, tags: Record<string, string>): Promise<string> {
    const d = this.desiredProjection(resource);
    if (d['subnetId'] === '') {
      throw new Error(
        `aws:ec2:NatGateway '${resourceIdOf(resource)}' requires attribute 'subnetId' ` +
          '(the public subnet the NAT lives in) — refusing to create (fail closed)',
      );
    }
    // HANDLER OWNS AN EIP: allocate a tagged VPC Elastic IP FIRST, then create
    // the NAT gateway on it (order matters). The EIP carries the identity tag
    // so teardown can find and release it even if the NAT is already gone.
    const alloc = await this.ec2.send(
      new AllocateAddressCommand({
        Domain: 'vpc',
        TagSpecifications: [
          {
            ResourceType: 'elastic-ip',
            Tags: toTagList({ Name: `${resourceIdOf(resource)}-eip`, ...tags }),
          },
        ],
      }),
    );
    const allocationId = alloc.AllocationId;
    if (allocationId === undefined) {
      throw new Error(`AllocateAddress returned no id for ${resource.logicalId} (fail closed)`);
    }
    try {
      const created = await this.ec2.send(
        new CreateNatGatewayCommand({
          SubnetId: d['subnetId'],
          AllocationId: allocationId,
          ConnectivityType: d['connectivityType'] as 'public' | 'private',
          TagSpecifications: [
            {
              ResourceType: 'natgateway',
              Tags: toTagList({ Name: resourceIdOf(resource), ...tags }),
            },
          ],
        }),
      );
      return created.NatGateway?.NatGatewayId ?? `nat:${resourceIdOf(resource)}`;
    } catch (err) {
      // The NAT never came up — release the orphaned EIP so it does not bill,
      // then surface the ORIGINAL create failure.
      try {
        await this.ec2.send(new ReleaseAddressCommand({ AllocationId: allocationId }));
      } catch {
        /* best effort — the original error is what matters */
      }
      throw err;
    }
  }

  async update(_resource: PlanResource, _current: ResourceState): Promise<void> {
    // No mutable attributes: the classifier never routes NAT drift to update
    // (every non-identity change is a gated replace).
  }

  async delete(resource: PlanResource, current: ResourceState): Promise<void> {
    // Find the handler-owned EIP(s) by identity tag BEFORE the NAT is gone —
    // robust even in a replace where the NAT was already torn down.
    const allocationIds = await this.ownedAllocationIds(resource);
    // DeleteNatGateway → bounded wait for 'deleted' → ReleaseAddress. AWS
    // rejects releasing an EIP still bound to a live NAT, hence the waiter.
    if (current.identifier !== undefined) {
      await this.ec2.send(new DeleteNatGatewayCommand({ NatGatewayId: current.identifier }));
      await this.waitForNatDeleted(resource);
    }
    // The EIP MUST be released or it bills once orphaned — fail closed if any
    // release fails so the teardown surfaces the leak instead of hiding it.
    for (const allocationId of allocationIds) {
      await this.ec2.send(new ReleaseAddressCommand({ AllocationId: allocationId }));
    }
  }

  /** Allocation ids of the handler-owned EIP(s), resolved by identity tag. */
  private async ownedAllocationIds(resource: PlanResource): Promise<string[]> {
    const found = await this.ec2.send(
      new DescribeAddressesCommand({
        Filters: [{ Name: `tag:${RESOURCE_TAG_KEY}`, Values: [resource.logicalId] }],
      }),
    );
    return (found.Addresses ?? [])
      .map((a) => a.AllocationId)
      .filter((id): id is string => id !== undefined);
  }

  /**
   * Bounded waiter: poll until the NAT has fully released its EIP (state
   * `deleted`/`failed`/absent — NOT merely left `pending`/`available`). A NAT in
   * `deleting` still holds its EIP, so returning there would race the subsequent
   * ReleaseAddress (M23.4 live finding). ≤ 10 min budget.
   */
  private async waitForNatDeleted(resource: PlanResource): Promise<void> {
    for (let attempt = 0; attempt < 60; attempt += 1) {
      const found = await this.ec2.send(
        new DescribeNatGatewaysCommand({
          Filter: [{ Name: `tag:${RESOURCE_TAG_KEY}`, Values: [resource.logicalId] }],
        }),
      );
      const bound = (found.NatGateways ?? []).filter((g) =>
        NAT_EIP_BOUND_STATES.some((s) => s === g.State),
      );
      if (bound.length === 0) return; // deleted/failed or gone → EIP freed → done
      await new Promise((resolve) => setTimeout(resolve, 10_000));
    }
    throw new Error(
      `NAT gateway for ${resource.logicalId} did not finish deleting within the ` +
        '10-minute waiter budget — refusing to release its EIP into an unknown state (fail closed)',
    );
  }
}
