/**
 * Plan assembly and canonical serialization (IEP-0011, ch. 14 §14.5).
 *
 * `buildPlan` is a pure function of exactly its arguments: the desired
 * provider plan, the state snapshot, and the determinism input vector
 * (CP-1). The emitted `content` serializes canonically — compact UTF-8
 * JSON, keys sorted lexicographically by Unicode code point (the same
 * `@iap/model` helper used for document canonical form), waves ordered by
 * dependency rank, entries within a wave sorted by resource identifier
 * (CP-2) — and `planId` is the SHA-256 of exactly those bytes, spelled
 * sha256:<hex>. Timestamps and signatures live only in the (optional)
 * envelope, which is never hashed (§14.5, PL-5); envelopes are created and
 * verified by `./envelope.js` with injected timestamps — never a clock.
 */

import { canonicalJsonStringify, compareCodePoints, sha256Hex } from '@iap/model';
import type { PlanResource, ProviderPlan } from '@iap/provider-sdk';
import {
  PLAN_API_VERSION,
  PLANNER_VERSION,
  computeInputsHash,
  computeStateIntegrity,
  sha256Digest,
} from './inputs.js';
import type { DeterminismInputs, PlanInputs, StateSnapshot } from './inputs.js';
import { determineActions } from './lifecycle.js';
import type { PlanAction, PlanActionEntry, ReversibilityClass } from './lifecycle.js';
import { riskRuleTableV1 } from './risk.js';
import { scheduleWaves } from './scheduler.js';

/** Reference to a destructive action (PL-3: always listed, never implied). */
export interface DestructiveActionRef {
  resource: string;
  action: 'replace' | 'delete';
  reversibility: ReversibilityClass;
}

/** Marker for an attribute whose value cannot appear in plan content. */
export interface UnknownValue {
  resource: string;
  attribute: string;
  /**
   * `output-binding`: generated by the substrate at apply time (bound to an
   * abstract output attribute). `sensitive`: declared sensitive by the
   * provider plan — the redaction rule is that plan content carries
   * attribute names only, never values, and sensitive attributes are
   * additionally marked here so reviewers see that a secret-bearing
   * attribute participates without ever seeing material (CE-6, PL-5).
   */
  reason: 'output-binding' | 'sensitive';
}

export interface RiskFactor {
  id: string;
  weight: number;
  resources: string[];
}

/** Deterministic risk annotation (IEP-0011 risk scoring). */
export interface RiskAnnotation {
  score: number;
  class: 'low' | 'medium' | 'high' | 'critical';
  factors: RiskFactor[];
}

/** Everything risk may depend on: the plan content minus the annotation itself. */
export type RiskInput = Omit<PlanContent, 'risk'>;

/**
 * The risk-scoring seam. Risk is a pure function of the plan content
 * (IEP-0011): the annotator receives every other content member and must
 * derive the annotation from nothing else — no clock, no environment, no
 * inference. The default is `riskRuleTableV1` (`./risk.js`), whose version
 * folds into `plannerVersion`; an injected replacement changes hashed
 * content and therefore every planId.
 */
export type RiskAnnotator = (content: RiskInput) => RiskAnnotation;

/** Cost delta with explicit unavailable/deferred markers (design decision 5). */
export interface CostDelta {
  status: 'unavailable' | 'deferred';
  reason: 'no-pricing-snapshot' | 'pricing-deferred-phase-10';
  pricingSnapshot?: string;
}

/** One security-relevant field change derived from the plan itself. */
export interface SecurityDelta {
  resource: string;
  field: string;
  /** Canonical document source path under spec.exposure or spec.encryption. */
  source: string;
}

export interface ComplianceFinding {
  framework: string;
  resource: string;
  detail: string;
}

/** Compliance delta: empty with an explicit deferred marker until Phase 11. */
export interface ComplianceDelta {
  deferred: 'phase-11';
  findings: ComplianceFinding[];
}

export interface PlanDeltas {
  cost: CostDelta;
  security: SecurityDelta[];
  compliance: ComplianceDelta;
}

export interface RollbackLimitation {
  resource: string;
  reason: string;
}

/**
 * Rollback contract (ch. 14 §14.6): the only strategy is re-planning to a
 * prior succeeded revision. `limitations` names every action that
 * re-planning cannot undo — one entry per irreversible action (delete of a
 * stateful resource with no restore source visible to the plan), so
 * unsupported rollback is always explicitly reported (Phase 7 exit
 * criterion 4), never discovered at rollback time.
 */
export interface PlanRollback {
  strategy: 're-plan-to-revision';
  limitations: RollbackLimitation[];
}

export const VERIFICATION_CHECKS = {
  create: 'created',
  'update-in-place': 'attributes-applied',
  replace: 'successor-ready',
  delete: 'removed',
  import: 'adopted',
} as const satisfies Record<PlanAction, string>;

export interface VerificationEntry {
  resource: string;
  check: (typeof VERIFICATION_CHECKS)[PlanAction];
}

/** Approval gate protecting one resource before execution (ch. 19 §19.6). */
export interface ApprovalRequirement {
  resource: string;
  gate: ApprovalGate;
}

/** Closed approval-gate vocabulary: one gate per destructive action. */
export const APPROVAL_GATES = [
  'stateful-replace',
  'stateful-delete',
  'destructive-replace',
  'destructive-delete',
] as const;
export type ApprovalGate = (typeof APPROVAL_GATES)[number];

/**
 * The deterministic approval rule: every destructive action requires
 * exactly one gate (IEP-0011: every destructiveActions entry carries its
 * required approval gate). Statefulness is read off the reversibility
 * class — the data-bearing classes map to the human gates of ch. 19 §19.6
 * (stateful replacement) and ch. 14 §14.6 (explicit data-loss acceptance);
 * the replacement-recoverable classes map to the plain destructive gates.
 * Total over the closed vocabularies; never derived from the risk class
 * (risk is computed over content that already includes these entries).
 */
export function approvalGateOf(
  action: 'replace' | 'delete',
  reversibility: ReversibilityClass,
): ApprovalGate {
  const dataBearing =
    reversibility === 'reversible-with-data-risk' ||
    reversibility === 'manual-recovery-required' ||
    reversibility === 'irreversible';
  if (action === 'replace') return dataBearing ? 'stateful-replace' : 'destructive-replace';
  return dataBearing ? 'stateful-delete' : 'destructive-delete';
}

/** The hashed plan content — canonical bytes of exactly this yield planId. */
export interface PlanContent {
  inputs: PlanInputs;
  waves: PlanActionEntry[][];
  destructiveActions: DestructiveActionRef[];
  unknownValues: UnknownValue[];
  risk: RiskAnnotation;
  deltas: PlanDeltas;
  rollback: PlanRollback;
  verification: VerificationEntry[];
  approvalsRequired: ApprovalRequirement[];
}

/** Envelope: timestamps and signature around the hashed content (never hashed). */
export interface PlanEnvelope {
  createdAt: string;
  expiresAt: string;
  signature: { keyId: string; alg: 'ed25519'; value: string };
}

/** The complete plan.iap.dev/v1 artifact. */
export interface PlanArtifact {
  apiVersion: typeof PLAN_API_VERSION;
  planId: string;
  envelope?: PlanEnvelope;
  content: PlanContent;
}

/* ------------------------------------------------------------------ */

/** Canonical byte projection of plan content (CP-2). */
export function canonicalPlanSerialization(content: PlanContent): string {
  return canonicalJsonStringify(content);
}

/** planId = sha256:<hex> over the canonical content serialization (§14.5). */
export function computePlanId(content: PlanContent): string {
  return sha256Digest(canonicalPlanSerialization(content));
}

function refuse(condition: boolean, message: string): void {
  if (condition) throw new TypeError(`planner input refused: ${message}`);
}

/**
 * Fail-closed input verification: the supplied artifacts must be internally
 * consistent and must be the artifacts the identity vector describes (the
 * plan-side counterpart of CP-4 — a planner never plans over inputs it
 * cannot vouch for).
 */
function verifyInputs(
  desired: ProviderPlan,
  state: StateSnapshot,
  inputs: DeterminismInputs,
): void {
  refuse(
    desired.formatVersion !== 1,
    `unsupported provider plan formatVersion ${String(desired.formatVersion)}`,
  );
  const unhashed: Record<string, unknown> = { ...desired };
  delete unhashed.planHash;
  refuse(
    sha256Hex(canonicalJsonStringify(unhashed)) !== desired.planHash,
    'provider plan planHash does not verify against its content',
  );
  refuse(
    computeStateIntegrity(state.objects) !== state.integrity,
    'state snapshot integrity hash does not verify against its objects (ch. 13 §13.1: treated as corruption)',
  );
  refuse(
    inputs.documentHash !== `sha256:${desired.documentHash}`,
    'inputs.documentHash does not match the provider plan documentHash',
  );
  refuse(
    inputs.target.provider !== desired.provider,
    'inputs.target.provider does not match the provider plan',
  );
  refuse(
    inputs.target.profile !== desired.profile,
    'inputs.target.profile does not match the provider plan profile',
  );
  refuse(
    inputs.mappingVersions[desired.provider] !== desired.mappingVersion,
    `inputs.mappingVersions must record ${desired.provider}@${desired.mappingVersion}`,
  );
  refuse(
    inputs.stateRevision !== state.revision,
    'inputs.stateRevision does not match the state snapshot revision',
  );
  refuse(
    inputs.stateIntegrity !== state.integrity,
    'inputs.stateIntegrity does not match the state snapshot integrity',
  );
  refuse(
    inputs.plannerVersion !== PLANNER_VERSION,
    `inputs.plannerVersion must be this implementation's version (${PLANNER_VERSION})`,
  );
}

function collectUnknownValues(desired: ProviderPlan, actions: PlanActionEntry[]): UnknownValue[] {
  const scheduled = new Set(
    actions.filter((entry) => entry.action !== 'delete').map((entry) => entry.resource),
  );
  const byKey = new Map<string, UnknownValue>();
  const add = (value: UnknownValue): void => {
    byKey.set(`${value.resource} ${value.attribute} ${value.reason}`, value);
  };
  // Output-bound attributes resolve only at apply time (late-bound).
  for (const bindings of Object.values(desired.outputBindings)) {
    for (const binding of Object.values(bindings)) {
      if (scheduled.has(binding.logicalId)) {
        add({
          resource: binding.logicalId,
          attribute: binding.attribute,
          reason: 'output-binding',
        });
      }
    }
  }
  // Sensitive attributes never enter plan content as values (CE-6, PL-5).
  for (const resource of desired.resources) {
    if (!scheduled.has(resource.logicalId)) continue;
    for (const attribute of resource.sensitiveFields) {
      add({ resource: resource.logicalId, attribute, reason: 'sensitive' });
    }
  }
  return [...byKey.values()].sort(
    (a, b) =>
      compareCodePoints(a.resource, b.resource) ||
      compareCodePoints(a.attribute, b.attribute) ||
      compareCodePoints(a.reason, b.reason),
  );
}

function isSecurityRelevant(source: string): boolean {
  return (
    source === 'spec.exposure' ||
    source.startsWith('spec.exposure.') ||
    source === 'spec.encryption' ||
    source.startsWith('spec.encryption.')
  );
}

function collectSecurityDeltas(
  byId: Map<string, PlanResource>,
  actions: PlanActionEntry[],
): SecurityDelta[] {
  const deltas: SecurityDelta[] = [];
  for (const entry of actions) {
    const resource = byId.get(entry.resource);
    if (resource === undefined) continue; // deletes carry no desired-side provenance
    for (const field of entry.fields) {
      const source = resource.provenance[field]?.source;
      if (source !== undefined && isSecurityRelevant(source)) {
        deltas.push({ resource: entry.resource, field, source });
      }
    }
  }
  return deltas.sort(
    (a, b) => compareCodePoints(a.resource, b.resource) || compareCodePoints(a.field, b.field),
  );
}

function costDelta(inputs: DeterminismInputs): CostDelta {
  if (inputs.pricingSnapshot === null) {
    // Never a silent zero (IEP-0011 cost impact; design decision 5).
    return { status: 'unavailable', reason: 'no-pricing-snapshot' };
  }
  // A snapshot is pinned, but pricing computation lands with Phase 10.
  return {
    status: 'deferred',
    reason: 'pricing-deferred-phase-10',
    pricingSnapshot: inputs.pricingSnapshot,
  };
}

export interface BuildPlanOptions {
  /** Desired provider-resource model from `applyMapping` (IEP-0012). */
  desired: ProviderPlan;
  /** Actual state (IEP-0010 subset); `emptySnapshot()` for first deployment. */
  state: StateSnapshot;
  /** The nine-element determinism input vector; `inputsHash` is computed here. */
  inputs: DeterminismInputs;
  /** Risk-scoring seam; defaults to the versioned rule table (riskRuleTableV1). */
  risk?: RiskAnnotator;
}

/**
 * Assemble the full `content` object: diff → lifecycle actions → waves →
 * destructive/unknown/delta/rollback/verification members → risk
 * annotation. Every collection is emitted in its documented deterministic
 * order, so `canonicalPlanSerialization(content)` is byte-stable across
 * runs, machines, environments, and key orderings (CP-2/CP-3).
 */
export function buildPlan(options: BuildPlanOptions): PlanContent {
  const { desired, state, inputs } = options;
  verifyInputs(desired, state, inputs);

  const actions = determineActions(desired, state);
  const waves = scheduleWaves(actions, desired, state);
  const byId = new Map<string, PlanResource>(
    desired.resources.map((resource) => [resource.logicalId, resource]),
  );

  const destructiveActions: DestructiveActionRef[] = actions
    .filter((entry) => entry.destructive)
    .map((entry) => ({
      resource: entry.resource,
      action: entry.action as 'replace' | 'delete',
      reversibility: entry.reversibility,
    }))
    .sort((a, b) => compareCodePoints(a.resource, b.resource));

  const verification: VerificationEntry[] = actions
    .map((entry) => ({ resource: entry.resource, check: VERIFICATION_CHECKS[entry.action] }))
    .sort((a, b) => compareCodePoints(a.resource, b.resource));

  // Unsupported rollback is explicitly reported (§14.6; exit criterion 4):
  // one limitation per irreversible action — re-planning to a prior revision
  // recreates the resource but cannot restore data no plan input can see.
  const limitations: RollbackLimitation[] = actions
    .filter((entry) => entry.reversibility === 'irreversible')
    .map((entry) => ({
      resource: entry.resource,
      reason: `irreversible ${entry.action} of a stateful resource: no restore source is visible to the plan, so re-planning to a prior revision cannot recover its data (ch. 14 §14.6)`,
    }))
    .sort((a, b) => compareCodePoints(a.resource, b.resource));

  // Every destructive action requires exactly one approval gate (IEP-0011;
  // ch. 19 §19.6). Non-destructive actions require none.
  const approvalsRequired: ApprovalRequirement[] = destructiveActions
    .map((entry) => ({
      resource: entry.resource,
      gate: approvalGateOf(entry.action, entry.reversibility),
    }))
    .sort((a, b) => compareCodePoints(a.resource, b.resource) || compareCodePoints(a.gate, b.gate));

  const planInputs: PlanInputs = {
    documentHash: inputs.documentHash,
    target: { provider: inputs.target.provider, profile: inputs.target.profile },
    profileHashes: sortRecord(inputs.profileHashes),
    policyBundles: sortRecord(inputs.policyBundles),
    extensionVersions: sortRecord(inputs.extensionVersions),
    mappingVersions: sortRecord(inputs.mappingVersions),
    discoverySnapshot: inputs.discoverySnapshot,
    pricingSnapshot: inputs.pricingSnapshot,
    stateRevision: inputs.stateRevision,
    stateIntegrity: inputs.stateIntegrity,
    plannerVersion: inputs.plannerVersion,
    inputsHash: computeInputsHash(inputs),
  };

  const base: RiskInput = {
    inputs: planInputs,
    waves,
    destructiveActions,
    unknownValues: collectUnknownValues(desired, actions),
    deltas: {
      cost: costDelta(inputs),
      security: collectSecurityDeltas(byId, actions),
      compliance: { deferred: 'phase-11', findings: [] },
    },
    rollback: { strategy: 're-plan-to-revision', limitations },
    verification,
    approvalsRequired,
  };

  const annotate = options.risk ?? riskRuleTableV1;
  return { ...base, risk: annotate(base) };
}

function sortRecord(record: Record<string, string>): Record<string, string> {
  const sorted: Record<string, string> = {};
  for (const key of Object.keys(record).sort(compareCodePoints)) {
    sorted[key] = record[key] as string;
  }
  return sorted;
}

/* ------------------------------------------------------------------ */

/**
 * Caller-supplied identities the `plan()` facade cannot derive from its
 * artifact arguments. Everything derivable is derived — documentHash,
 * target, and mappingVersions from the provider plan; stateRevision and
 * stateIntegrity from the snapshot; plannerVersion from this package — so
 * the facade cannot be handed a vector that contradicts its artifacts.
 */
export interface InputIdentities {
  /** Identity 2: profile name → sha256:<hex> of each merged profile definition. */
  profileHashes?: Record<string, string>;
  /** Identity 3: policy bundle name → version/hash in force. */
  policyBundles?: Record<string, string>;
  /** Identity 4: extension package namespace → version. */
  extensionVersions?: Record<string, string>;
  /** Identity 6: discovery snapshot id (never a live lookup — ch. 12 §12.2). */
  discoverySnapshot?: string | null;
  /** Identity 7: pricing snapshot id; omitted ⇒ deltas.cost is unavailable. */
  pricingSnapshot?: string | null;
}

export interface PlanOptions {
  /** Risk-scoring seam; defaults to the versioned rule table (riskRuleTableV1). */
  risk?: RiskAnnotator;
}

/**
 * The current nine-element identity vector for a (provider plan, snapshot,
 * caller identities) triple — everything derivable is derived, so the
 * vector can never contradict its artifacts. Shared by the `plan()` facade
 * and by `verifyPlan`, which recomputes exactly this vector before
 * execution (PL-2).
 */
export function deriveDeterminismInputs(
  providerPlan: ProviderPlan,
  stateSnapshot: StateSnapshot,
  identities: InputIdentities = {},
): DeterminismInputs {
  return {
    documentHash: `sha256:${providerPlan.documentHash}`,
    target: { provider: providerPlan.provider, profile: providerPlan.profile },
    profileHashes: identities.profileHashes ?? {},
    policyBundles: identities.policyBundles ?? {},
    extensionVersions: identities.extensionVersions ?? {},
    mappingVersions: { [providerPlan.provider]: providerPlan.mappingVersion },
    discoverySnapshot: identities.discoverySnapshot ?? null,
    pricingSnapshot: identities.pricingSnapshot ?? null,
    stateRevision: stateSnapshot.revision,
    stateIntegrity: stateSnapshot.integrity,
    plannerVersion: PLANNER_VERSION,
  };
}

/**
 * The planner facade: desired provider plan + state snapshot + explicit
 * input identities → a complete, schema-valid plan.iap.dev/v1 artifact
 * (without envelope — `signPlan` attaches one with injected timestamps).
 */
export function plan(
  providerPlan: ProviderPlan,
  stateSnapshot: StateSnapshot,
  identities: InputIdentities = {},
  options: PlanOptions = {},
): PlanArtifact {
  const content = buildPlan({
    desired: providerPlan,
    state: stateSnapshot,
    inputs: deriveDeterminismInputs(providerPlan, stateSnapshot, identities),
    ...(options.risk !== undefined ? { risk: options.risk } : {}),
  });
  return { apiVersion: PLAN_API_VERSION, planId: computePlanId(content), content };
}
